### ISSUE TITLE
on the create project page none of the buttons appear to work

### ISSUE THREAD

**Issue by satra** [neuroanatomy/BrainBox#101]
firefoxESR 45.3.0 on linux (centos 7.2)

none of the buttons are active.

**Comment by r03ert0** [comment]
there are two pages involved in the creation of a project:

1. http://brainbox.pasteur.fr/project/new

and then

2. http://brainbox.pasteur.fr/project/[Project Name]/settings

is it the buttons in the /new page that do not work? normally, the 'Cancel' button should take you back to the home page, and the 'Create Project' button should take you to the /settings page. The only case in which the 'Create Project' button should be disabled is when the project name is already used or contains non-authorised caracters

in the /settings page, sometimes, when the number of files to import is too large (the case of ABIDE, for example), the completion of the actions takes so long that you may have the impression that it's not working... we should provide some progress feedback (or find the way of making the process faster...)

**Comment by r03ert0** [comment]
can you check if this bug still exists?

**Comment by satra** [comment]
same exact issue still.

**Comment by r03ert0** [comment]
is it in this page?
http://brainbox.pasteur.fr/project/new
Here the buttons are active in Safari, Chrome and Firefox (dev. edition)
