### ISSUE TITLE
Change jQuery Promises into Ecma Promises

### ISSUE THREAD

**Issue by r03ert0** [neuroanatomy/BrainBox#156]
### Is this a feature request or a bug report? 
This is an enhancement request

### What is the current behaviour?
Currently brainbox uses jQuery promises, which look like this:
```
function foo() {
  var def = new $.Deferred();
  if(result_of_async_process_is_ok) {
    def.resolve();
  } else {
    def.reject();
  }
  return def.promise();
}
```

### What is the expected or desired behavior?

Use standard ES promises, which look like:

```
functio foo() {
  var pr = new Promise(function(resolve, reject) {
    if(result_of_async_process_is_ok) {
      resolve();
    } else {
      reject();
    }
    return pr;
  });
```
Other than that, brainbox uses the $.when promises, which should be replaced with Promise.all([]).

**Comment by tulikavijay** [comment]
I would like to work on this :)

**Comment by r03ert0** [comment]
nice!

**Comment by tulikavijay** [comment]
can you review my PR please? i have to make more changes i would like to know if i am doing it right. 
Also i cant figure out how to convert this one : [L296](https://github.com/OpenNeuroLab/BrainBox/pull/180/commits/386fc36ebc83b2ac2036bc2eb9c9511c53ccf7e4#diff-3b5f8ae9188aeafe04ed573ce5603730L296)
thankyou.
