### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by katjaq** [neuroanatomy/BrainBox#186]
adding pictures to our GitHub repo
![brainboxgithub](https://user-images.githubusercontent.com/6297454/32104270-96db0afa-bb1b-11e7-8911-786d420c308a.png)

**Comment by katjaq** [comment]
<img width="1147" alt="screen shot 2017-12-12 at 07 59 24" src="https://user-images.githubusercontent.com/6297454/33871747-1f8d8e74-df14-11e7-8002-111ba96c4cb0.png">

**Comment by katjaq** [comment]
current user interface
![screen shot 2017-12-12 at 14 38 45](https://user-images.githubusercontent.com/6297454/33887521-463476ba-df4a-11e7-9c80-592770978bd8.png)

**Comment by r03ert0** [comment]
this issue doesn't need to be open...
