### ISSUE TITLE
2 tools not working in current working repo

### ISSUE THREAD

**Issue by katjaq** [neuroanatomy/BrainBox#208]
The measure tool does currently not do anything. No reaction on click, drag or return key. No error message.

The surface reconstruction is not working. Error message:
wrkr: SurfaceNets
surfacenets-worker.js:40 Uncaught TypeError: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': Value at index 0 does not have a transferable type.
    at computeMesh (surfacenets-worker.js:40)
    at configureNifti (surfacenets-worker.js:197)
    at init (surfacenets-worker.js:30)
    at surfacenets-worker.js:8
surfacenets-worker.js:40 Uncaught TypeError: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': Value at index 0 does not have a transferable type.
default.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by r03ert0** [comment]
fixed by commit 3c7022e (measure tool) and commit 648dfa0 (render3d)
