### ISSUE TITLE
wrong tooltip when editing rights for annotations or mri files

### ISSUE THREAD

**Issue by ntraut** [neuroanatomy/BrainBox#285]
when editing project rights, the tooltip is always about collaborators even if the editing is on annotations or mri files
![image](https://user-images.githubusercontent.com/22977927/122907816-cc674b80-d353-11eb-8456-42316b122eeb.png)

**Comment by katjaq** [comment]
oh, i fixed this one already 👀 Will check where that went! Thanks for the ping @ntraut :)

**Comment by katjaq** [comment]
fixed in PR #286 :)
will close the issue. Thank you again for bringing it up @ntraut 🚀
