### ISSUE TITLE
impossibility to add github labels for non collaborators

### ISSUE THREAD

**Issue by ntraut** [neuroanatomy/BrainBox#304]
### Current behaviour

* If this is a bug, please explain how to reproduce the problem 
    * Which tools did you use in which sequence?
    * Is the error concerning a text or a volume annotation? 
    * Which label set has been used for the volume annotation (if applicable)?
    * What is the type and resolution of your data? (Can you provide a link to your data?)
    * Do not include sensitive information.
    * Upload the browser error message if you are familiar with web developer tools.

currently simple github users cannot add labels to the issues they create unless they are collaborators, and apparently there is no way to give them the right:
https://github.com/isaacs/github/issues/148

### Expected behaviour
we should not ask to users to do something they cannot do, maybe we could add "if you are a collaborator"?

### Version information (for bug reports)

current

**Comment by katjaq** [comment]
oh wow! Never realised that only contributors can label issues. True that our users usually use other channels than GitHub to report bugs and unexpected behaviour to us. and everyone adding an issue here may be a contributor. Thank you so much for finding this @ntraut ! ⭐ i will adapt the issue template.

**Comment by ntraut** [comment]
thank you, personally i already got the problem, not anymore but we are very few to be have collaborator rights, so many other users should have experienced that issue.

**Comment by katjaq** [comment]
Thank you again for the note. Fixed in [#351ff20](https://github.com/neuroanatomy/BrainBox/commit/351ff2059efa78e2689b77a8e6f489c0b6870010) now :)

**Comment by AuracleTech** [comment]
So wait why is the thread closed on [issue 148](https://github.com/isaacs/github/issues/148), not sure I follow there...
I'm waiting for this impatiently... I am really tired of opening tickets for improvements / request as issues

**Comment by ntraut** [comment]
@AuracleTech github has removed the possibility to discuss on its thread but we are not responsible for this, here we closed our issue because we found another way to fulfill our need.

**Comment by AuracleTech** [comment]
I see
Big rip we GitHub takes years to implement this
