### ISSUE TITLE
Save after import data from csv broken

### ISSUE THREAD

**Issue by katjaq** [neuroanatomy/BrainBox#320]
When adding an mri manually to a project, I can save changes. When uploading a csv file, import is all fine, but I cannot save the changes. `Unable to save: Error 500: Invalid file name` which is probably not the error 😅 . 
I know @dhovart had this on the radar, maybe you have an idea? I sent you the example file.

**Comment by r03ert0** [comment]
the problem was CRLF characters at the end of the lines of the csv file, instead of the expected LF.
I'll close this issue and open a new one asking for an enhancement to take that case into account automatically.
