### ISSUE TITLE
Security certificate out of date

### ISSUE THREAD

**Issue by NevMagi** [neuroanatomy/BrainBox#341]
**Current behaviour**
The BrainBox security certificate is out of date since yesterday:

Attackers might be trying to steal your information from brainbox.pasteur.fr (for example, passwords, messages or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_DATE_INVALID
This server could not prove that it is brainbox.pasteur.fr; its security certificate expired in the last day. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Tuesday, 24 May 2022. Does that look right? If not, you should correct your system's clock and then refresh this page.

Version information (for bug reports)
Chrome Version 99.0.4844.84:
**macOS BigSur Version 11.4 (20F71)*:

**Comment by katjaq** [comment]
Hey! Thank you for the ping! GitHub decreased the time for renewals of the certificates and it seems we still haven't got the rhythm right! 😅  Will do asap. Thanks.

**Comment by katjaq** [comment]
Security certificate updated a couple of days ago, but forgot to ping here, sorry. All good again :)
