### ISSUE TITLE
newly added brains can only be viewed and segmented once until they are added to a project

### ISSUE THREAD

**Issue by ntraut** [neuroanatomy/BrainBox#343]
the second time we try to access the brain we get a blank page with "Authorization required". we can access the brain again once it gets added to a project, even if the project rights for anyone are null.
this behaviour doesn't seem to make a lot of sense to me, so I think it's a bug.

**Comment by dhovart** [comment]
Hi, will look into it. It indeed seems to be buggy.
What do you mean by "the project rights are null"?
You do not have files view permissions?

**Comment by ntraut** [comment]
I just mean if in the project no right is given to the user anyone

**Comment by dhovart** [comment]
I looked into it and I saw I'm retrieving a list of all projects containing the source file, even the "archived" one (that have the "backup" property set to true). Adding `backup: { $exists: 0 }}` there fix the issue: https://github.com/neuroanatomy/BrainBox/blob/master/controller/mri/mri.controller.js#L281

Concerning the initial bug: we shouldn't indeed maybe not be able to add a brain this way without adding it to a project first. What would you suggest ? @r03ert0 @katjaq

**Comment by dhovart** [comment]
@r03ert0  We let user access the MRI page if there are some projects that set the MRI file as visible by anyone or if he is the owner or a collaborator.
Apparently also if it's a new brain that was not yet added to brainbox.

But once the brain is saved, it's not accessible anymore because it's not related to any project and so we determine it's not public (no project listing it as viewable by anyone).

You were asking for this changes because you didn't want sensitive brain data to leak. Should we still display the brain if it's not linked to any project? Should we remove in this case this "Authorization required" message ?

**Comment by r03ert0** [comment]
The current behaviour in BrainBox is that if you have the URL for a brain, you can see it. What you can't see are the annotations. And what we should ensure is that we do not leak URLs (for example, no listing of all MRIs in BrainBox).
The problem that we had the last time was that one collaborator made a public project including one of our brains where we didn't want to share the URLs. By adding the URL to a public project, the URL would become available to anyone. We decided to add an advertisement, which I think is the reasonable thing to do.

I don't want to forbid the visualisation of a brain for which you have the URL. That would render the URL field in the landing page pretty useless. The only way of adding a brain would be by creating a project first, and adding the URL there. Only then you would be able to use the URL field in the landing page, which doesn't make a lot of sense.

**Comment by dhovart** [comment]
I'll remove the check that prevent you from accessing the MRI if files are
not set as viewable by anyone in another commit in the PR above (but keep
the warning in place)

Em qui., 9 de jun. de 2022 19:08, Roberto Toro ***@***.***>
escreveu:

> The current behaviour in BrainBox is that if you have the URL for a brain,
> you can see it. What you can't see are the annotations. And what we should
> ensure is that we do not leak URLs (for example, no listing of all MRIs in
> BrainBox).
> The problem that we had the last time was that one collaborator made a
> public project including one of our brains where we didn't want to share
> the URLs. By adding the URL to a public project, the URL would become
> available to anyone. We decided to add an advertisement, which I think is
> the reasonable thing to do.
>
> I don't want to forbid the visualisation of a brain for which you have the
> URL. That would render the URL field in the landing page pretty useless.
> The only way of adding a brain would be by creating a project first, and
> adding the URL there. Only then you would be able to use the URL field in
> the landing page, which doesn't make a lot of sense.

**Comment by r03ert0** [comment]
that's perfectly fine, then. Those are the brains we provide to people so that they can give BrainBox a try.

**Comment by ntraut** [comment]
In the production brainbox it's currently impossible to load the first one (https://zenodo.org/record/44855/files/MRI-n4.nii.gz) but that seems to be another bug. client side we are simply keeping waiting for an answer and server side this error is reported:
```
TypeError: Cannot read properties of null (reading 'shortname')
    at /var/www/html/brainbox/services/BrainboxAccessControlService.js:51:46
    at Array.find (<anonymous>)
    at /var/www/html/brainbox/services/BrainboxAccessControlService.js:51:32
    at Array.map (<anonymous>)
    at Function.setVolumeAnnotationsAccessByProjects (/var/www/html/brainbox/services/BrainboxAccessControlService.js:50:33)
    at mri (/var/www/html/brainbox/controller/mri/mri.controller.js:290:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by dhovart** [comment]
Both issues are fixed with #344, if you want to give it a look.

**Comment by dhovart** [comment]
@ntraut looking into this one as well

**Comment by ntraut** [comment]
It looks like the bugs mentioned above are fixed with #344, but there is still the function `hasAccesstoFileIfAllowedByAllProjects` for which I have hard time to find the purpose:
https://github.com/neuroanatomy/BrainBox/blob/7eb3228990f88a6994e588a10518ace7348c0618/services/BrainboxAccessControlService.js#L6-L19

This function is used for example in the function `getUserFilesSlice`. Why should the user to get an MRI listed in its projects have view access on all the projects using this MRI? Why one project giving him access is not enough?

It makes even less sense to me when I see that the infos that I get when I go to https://brainbox.pasteur.fr/user/json/ntraut/files?start=0&length=10 are only url, name, included and volDimensions, nothing related to specific annotations in a particular project...

**Comment by dhovart** [comment]
Hello Nicolas! It's a good question actually, and I don't really know how
to answer it. I didn't introduce this one, just moved it in the
AccessControl service.
I trust you if you say it makes little sense to keep it in place. In the
same service I believe we have `hasAccesstoFileIfAllowedBySomeProjects` -
so maybe that would make more sense to use this one instead?

I can only look into this further only tomorrow, have a nice end of weekend

Le dim. 12 juin 2022 à 16:25, Nicolas Traut ***@***.***> a
écrit :

**Comment by r03ert0** [comment]
is it possible to find where that function is used? That may help see what it's supposed to do
