### ISSUE TITLE
websocket are incorrectly reported as not supported

### ISSUE THREAD

**Issue by ntraut** [neuroanatomy/BrainBox#345]
### Current behaviour

To check if the websockets are working, a connection is attempted to wss://echo.websocket.org which is down, so the problem is on the remote server side and not in brainbox. websocket.org

### Expected behaviour

websocket.org should not be used to check websockets

**Comment by r03ert0** [comment]
but then we wouldn't know if brainbox websocket server is down...
maybe we could test several?

**Comment by ntraut** [comment]
I think the primary goal is to test if the client can use websockets but if the brainbox web socket server is down we will still get connection failure reported, which is more or less what we want. even if the test will not allow to directly isolate a client failure and a server failure, a simple go to a site like https://websocketstest.com/ will allow to test the client. if the brainbox web socket server is down, it is true that users will get incorrect report that their client does not enable web sockets, but anyway that will mean that there is a problem with the brainbox server, and the goal is that the brainbox server is working, so at least we will not get a reported error for nothing.

**Comment by r03ert0** [comment]
that's correct 😅
thinking about the reason why I added that test to begin with: at that time I wasn't sure if my implementation of websockets was legit, so I wanted to have some external way of verifying it. But now there's no real reason for it.
