### ISSUE TITLE
improper orientation

### ISSUE THREAD

**Issue by satra** [neuroanatomy/BrainBox#57]
http://brainbox.pasteur.fr/mri?url=https://s3.amazonaws.com/fcp-indi-new/data/Projects/INDI/HypnosisBarrios/RawData/sub-0030689/anat/sub-0030689_T1w.nii.gz

![image](https://cloud.githubusercontent.com/assets/184063/19406681/7402b63c-9258-11e6-9159-c9159bc36848.png)

**Comment by satra** [comment]
this project is still off. either the nifti's are incorrect (i'll check with another viewer), or sth is up with the nifti reader:

http://brainbox.pasteur.fr/mri?url=https://s3.amazonaws.com/fcp-indi-new/data/Projects/INDI/HypnosisBarrios/RawData/sub-0030689/anat/sub-0030689_T1w.nii.gz

**Comment by r03ert0** [comment]
it seems that MRI doesn't exist anymore in amazon...
